// Code generated by MockGen. DO NOT EDIT.
// Source: business_connection_store.go
//
// Generated by this command:
//
//	mockgen -source=business_connection_store.go -destination=mock/business_connection_store.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "noirbot/internal/domain/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBusinessConnectionStore is a mock of BusinessConnectionStore interface.
type MockBusinessConnectionStore struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessConnectionStoreMockRecorder
	isgomock struct{}
}

// MockBusinessConnectionStoreMockRecorder is the mock recorder for MockBusinessConnectionStore.
type MockBusinessConnectionStoreMockRecorder struct {
	mock *MockBusinessConnectionStore
}

// NewMockBusinessConnectionStore creates a new mock instance.
func NewMockBusinessConnectionStore(ctrl *gomock.Controller) *MockBusinessConnectionStore {
	mock := &MockBusinessConnectionStore{ctrl: ctrl}
	mock.recorder = &MockBusinessConnectionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusinessConnectionStore) EXPECT() *MockBusinessConnectionStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBusinessConnectionStore) Delete(ctx context.Context, connectionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, connectionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBusinessConnectionStoreMockRecorder) Delete(ctx, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBusinessConnectionStore)(nil).Delete), ctx, connectionID)
}

// Get mocks base method.
func (m *MockBusinessConnectionStore) Get(ctx context.Context, connectionID string) (model.BusinessConnection, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, connectionID)
	ret0, _ := ret[0].(model.BusinessConnection)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockBusinessConnectionStoreMockRecorder) Get(ctx, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBusinessConnectionStore)(nil).Get), ctx, connectionID)
}

// Put mocks base method.
func (m *MockBusinessConnectionStore) Put(ctx context.Context, conn model.BusinessConnection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, conn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockBusinessConnectionStoreMockRecorder) Put(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockBusinessConnectionStore)(nil).Put), ctx, conn)
}
