// Code generated by MockGen. DO NOT EDIT.
// Source: business_account_reader.go
//
// Generated by this command:
//
//	mockgen -source=business_account_reader.go -destination=mock/business_account_reader.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "noirbot/internal/domain/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBusinessAccountReader is a mock of BusinessAccountReader interface.
type MockBusinessAccountReader struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessAccountReaderMockRecorder
	isgomock struct{}
}

// MockBusinessAccountReaderMockRecorder is the mock recorder for MockBusinessAccountReader.
type MockBusinessAccountReaderMockRecorder struct {
	mock *MockBusinessAccountReader
}

// NewMockBusinessAccountReader creates a new mock instance.
func NewMockBusinessAccountReader(ctrl *gomock.Controller) *MockBusinessAccountReader {
	mock := &MockBusinessAccountReader{ctrl: ctrl}
	mock.recorder = &MockBusinessAccountReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusinessAccountReader) EXPECT() *MockBusinessAccountReaderMockRecorder {
	return m.recorder
}

// GetConnection mocks base method.
func (m *MockBusinessAccountReader) GetConnection(ctx context.Context, connectionID string) (model.BusinessConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx, connectionID)
	ret0, _ := ret[0].(model.BusinessConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockBusinessAccountReaderMockRecorder) GetConnection(ctx, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockBusinessAccountReader)(nil).GetConnection), ctx, connectionID)
}
