// Code generated by MockGen. DO NOT EDIT.
// Source: business_sender.go
//
// Generated by this command:
//
//	mockgen -source=business_sender.go -destination=mock/business_sender.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "noirbot/internal/domain/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBusinessSender is a mock of BusinessSender interface.
type MockBusinessSender struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessSenderMockRecorder
	isgomock struct{}
}

// MockBusinessSenderMockRecorder is the mock recorder for MockBusinessSender.
type MockBusinessSenderMockRecorder struct {
	mock *MockBusinessSender
}

// NewMockBusinessSender creates a new mock instance.
func NewMockBusinessSender(ctrl *gomock.Controller) *MockBusinessSender {
	mock := &MockBusinessSender{ctrl: ctrl}
	mock.recorder = &MockBusinessSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusinessSender) EXPECT() *MockBusinessSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockBusinessSender) Send(ctx context.Context, draft model.ReplyDraft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, draft)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockBusinessSenderMockRecorder) Send(ctx, draft any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBusinessSender)(nil).Send), ctx, draft)
}
