// Code generated by MockGen. DO NOT EDIT.
// Source: message_window_store.go
//
// Generated by this command:
//
//	mockgen -source=message_window_store.go -destination=mock/message_window_store.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "noirbot/internal/domain/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageWindowStore is a mock of MessageWindowStore interface.
type MockMessageWindowStore struct {
	ctrl     *gomock.Controller
	recorder *MockMessageWindowStoreMockRecorder
	isgomock struct{}
}

// MockMessageWindowStoreMockRecorder is the mock recorder for MockMessageWindowStore.
type MockMessageWindowStoreMockRecorder struct {
	mock *MockMessageWindowStore
}

// NewMockMessageWindowStore creates a new mock instance.
func NewMockMessageWindowStore(ctrl *gomock.Controller) *MockMessageWindowStore {
	mock := &MockMessageWindowStore{ctrl: ctrl}
	mock.recorder = &MockMessageWindowStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageWindowStore) EXPECT() *MockMessageWindowStoreMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockMessageWindowStore) Append(ctx context.Context, ownerID, guestID int64, msg model.IncomingMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, ownerID, guestID, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockMessageWindowStoreMockRecorder) Append(ctx, ownerID, guestID, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockMessageWindowStore)(nil).Append), ctx, ownerID, guestID, msg)
}

// CountSince mocks base method.
func (m *MockMessageWindowStore) CountSince(ctx context.Context, ownerID, guestID int64, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSince", ctx, ownerID, guestID, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSince indicates an expected call of CountSince.
func (mr *MockMessageWindowStoreMockRecorder) CountSince(ctx, ownerID, guestID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSince", reflect.TypeOf((*MockMessageWindowStore)(nil).CountSince), ctx, ownerID, guestID, since)
}
