// Code generated by MockGen. DO NOT EDIT.
// Source: owner_whitelist.go
//
// Generated by this command:
//
//	mockgen -source=owner_whitelist.go -destination=mock/owner_whitelist.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOwnerWhitelist is a mock of OwnerWhitelist interface.
type MockOwnerWhitelist struct {
	ctrl     *gomock.Controller
	recorder *MockOwnerWhitelistMockRecorder
	isgomock struct{}
}

// MockOwnerWhitelistMockRecorder is the mock recorder for MockOwnerWhitelist.
type MockOwnerWhitelistMockRecorder struct {
	mock *MockOwnerWhitelist
}

// NewMockOwnerWhitelist creates a new mock instance.
func NewMockOwnerWhitelist(ctrl *gomock.Controller) *MockOwnerWhitelist {
	mock := &MockOwnerWhitelist{ctrl: ctrl}
	mock.recorder = &MockOwnerWhitelistMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnerWhitelist) EXPECT() *MockOwnerWhitelistMockRecorder {
	return m.recorder
}

// IsAllowed mocks base method.
func (m *MockOwnerWhitelist) IsAllowed(ctx context.Context, ownerID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAllowed", ctx, ownerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAllowed indicates an expected call of IsAllowed.
func (mr *MockOwnerWhitelistMockRecorder) IsAllowed(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAllowed", reflect.TypeOf((*MockOwnerWhitelist)(nil).IsAllowed), ctx, ownerID)
}
