// Code generated by MockGen. DO NOT EDIT.
// Source: voice_reply_window_store.go
//
// Generated by this command:
//
//	mockgen -source=voice_reply_window_store.go -destination=mock/voice_reply_window_store.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockVoiceReplyWindowStore is a mock of VoiceReplyWindowStore interface.
type MockVoiceReplyWindowStore struct {
	ctrl     *gomock.Controller
	recorder *MockVoiceReplyWindowStoreMockRecorder
	isgomock struct{}
}

// MockVoiceReplyWindowStoreMockRecorder is the mock recorder for MockVoiceReplyWindowStore.
type MockVoiceReplyWindowStoreMockRecorder struct {
	mock *MockVoiceReplyWindowStore
}

// NewMockVoiceReplyWindowStore creates a new mock instance.
func NewMockVoiceReplyWindowStore(ctrl *gomock.Controller) *MockVoiceReplyWindowStore {
	mock := &MockVoiceReplyWindowStore{ctrl: ctrl}
	mock.recorder = &MockVoiceReplyWindowStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoiceReplyWindowStore) EXPECT() *MockVoiceReplyWindowStoreMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockVoiceReplyWindowStore) Release(ctx context.Context, connectionID string, guestID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, connectionID, guestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockVoiceReplyWindowStoreMockRecorder) Release(ctx, connectionID, guestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockVoiceReplyWindowStore)(nil).Release), ctx, connectionID, guestID)
}

// TryEnter mocks base method.
func (m *MockVoiceReplyWindowStore) TryEnter(ctx context.Context, connectionID string, guestID int64, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryEnter", ctx, connectionID, guestID, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryEnter indicates an expected call of TryEnter.
func (mr *MockVoiceReplyWindowStoreMockRecorder) TryEnter(ctx, connectionID, guestID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryEnter", reflect.TypeOf((*MockVoiceReplyWindowStore)(nil).TryEnter), ctx, connectionID, guestID, ttl)
}
