// Code generated by MockGen. DO NOT EDIT.
// Source: voice_downloader.go
//
// Generated by this command:
//
//	mockgen -source=voice_downloader.go -destination=mock/voice_downloader.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVoiceDownloader is a mock of VoiceDownloader interface.
type MockVoiceDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockVoiceDownloaderMockRecorder
	isgomock struct{}
}

// MockVoiceDownloaderMockRecorder is the mock recorder for MockVoiceDownloader.
type MockVoiceDownloaderMockRecorder struct {
	mock *MockVoiceDownloader
}

// NewMockVoiceDownloader creates a new mock instance.
func NewMockVoiceDownloader(ctrl *gomock.Controller) *MockVoiceDownloader {
	mock := &MockVoiceDownloader{ctrl: ctrl}
	mock.recorder = &MockVoiceDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoiceDownloader) EXPECT() *MockVoiceDownloaderMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockVoiceDownloader) Download(ctx context.Context, fileID string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, fileID)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockVoiceDownloaderMockRecorder) Download(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockVoiceDownloader)(nil).Download), ctx, fileID)
}
